# .github/workflows/close-prs.yml
name: Auto Close PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest

    steps:
    - name: Wait before closing (to let other checks run)
      run: sleep 60  # wait 60 seconds

    - name: Comment and Close PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "👋 Thanks for your submission! We review PRs manually but do not merge them. Your PR has been closed automatically after review."
          });
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            state: 'closed'
          });
